name: "Smart-House buttons"
version: "0.1.0"
slug: folder
description: >-
  "A rather hacky way of getting my old Carlo Gavazzi smart-house buttons to trigger Home Assistant."
arch:
  - amd64
  - aarch64
  - armhf
url: "https://github.com/andrioid/hassio-addons"
ports:
  123/tcp: 123
map:
  - config:rw
  - ssl
schema:
  modbus_host: str
options:
  modbus_host: ""
