name: "Smart-House buttons"
version: "0.1.9"
slug: folder
init: false
description: >-
  "A (rather hacky) way of using wall-switches from a Carlo Gavazzi smart-house to send MQTT messages to Zigbee relays."
arch:
  - amd64
  - aarch64
  - armhf
url: "https://github.com/andrioid/hassio-addons"
map:
  - config:rw
  - ssl
schema:
  modbus_host: str
options:
  modbus_host: ""
services:
  - mqtt:need
